INSERT INTO public.department
(id, "name")
VALUES
(1, 'Amazonas'),
(2, 'Antioquia'),
(3, 'Arauca'),
(4, 'Atlántico'),
(5, 'Bolívar'),
(6, 'Boyacá'),
(7, 'Caldas'),
(8, 'Caquetá'),
(9, 'Casanare'),
(10, 'Cauca'),
(11, 'Cesar'),
(12, 'Chocó'),
(13, 'Cundinamarca'),
(14, 'Córdoba'),
(15, 'Distrito Capital de Bogotá'),
(16, 'Guainía'),
(17, 'Guaviare'),
(18, 'Huila'),
(19, 'La Guajira'),
(20, 'Magdalena'),
(21, 'Meta'),
(22, 'Nariño'),
(23, 'Norte de Santander'),
(25, 'Putumayo'),
(26, 'Quindío'),
(27, 'Risaralda'),
(28, 'San Andrés, Providencia y Santa Catalina'),
(29, 'Santander'),
(30, 'Sucre'),
(31, 'Tolima'),
(32, 'Valle del Cauca'),
(33, 'Vaupés'),
(34, 'Vichada')
