create table athlete (id integer not null, birth_date varchar(255), id_number varchar(255), last_name varchar(255), name varchar(255), picture_url varchar(255), sex smallint check (sex between 0 and 1), weight float(53) not null, fk_belt_grade integer, fk_club integer, fk_document_type integer, fk_country integer, primary key (id));
create table categories (id integer not null, sex smallint check (sex between 0 and 1), fk_category_age integer, fk_category_belt_grade integer, fk_category_weight integer, primary key (id));
create table championship (id integer not null, end_event_date timestamp(6), name varchar(255), start_event_date timestamp(6), fk_club integer not null, fk_location integer not null, primary key (id));
create table club (id integer not null, email varchar(255), name varchar(255), fk_country integer not null, fk_municipality integer, primary key (id));
alter table if exists location add column municipality_id integer;
create table municipality (id integer not null, code integer, name varchar(255), fk_department integer, primary key (id));
create table representative (id integer not null, document_number varchar(255), last_nane varchar(255), name varchar(255), phone_number varchar(255), fk_club integer not null, fk_document_type integer not null, primary key (id));
alter table if exists location drop constraint if exists UKlxduifr1oahk3fyxrnwei7trk;
alter table if exists location add constraint UKlxduifr1oahk3fyxrnwei7trk unique (municipality_id);
create sequence athlete_seq start with 1 increment by 50;
create sequence categories_seq start with 1 increment by 50;
create sequence championship_seq start with 1 increment by 50;
create sequence club_seq start with 1 increment by 50;
create sequence municipality_seq start with 1 increment by 50;
create sequence representative_seq start with 1 increment by 50;
alter table if exists athlete add constraint FKdy2jjim1bs4uua4isny0x70y9 foreign key (fk_belt_grade) references belt_grade;
alter table if exists athlete add constraint FKeqmqebp2jbghwjsey1fgv42rh foreign key (fk_club) references club;
alter table if exists athlete add constraint FKjqw93h9xfgwbhyo5tiqkiiuql foreign key (fk_document_type) references document_type;
alter table if exists athlete add constraint FKb2gqr88jmxe9m583a8866048r foreign key (fk_country) references country;
alter table if exists categories add constraint FK8uxubv1y5eqp75enx4isfg99d foreign key (fk_category_age) references category_age;
alter table if exists categories add constraint FKcopmh6sop7af5966dbc7mdpj8 foreign key (fk_category_belt_grade) references category_belt_grade;
alter table if exists categories add constraint FKbtoio1dpyep57tu765y5g4drr foreign key (fk_category_weight) references category_weight;
alter table if exists championship add constraint FKio3b5rwak8wl49adodhk7xgmi foreign key (fk_club) references club;
alter table if exists championship add constraint FK6crwfyvqtjqu0w1tauho6vpxv foreign key (fk_location) references location;
alter table if exists club add constraint FK7syjecp1a87lp35fdyxtputl4 foreign key (fk_country) references country;
alter table if exists club add constraint FK5rny420umgc5r0iet5qenbbly foreign key (fk_municipality) references municipality;
alter table if exists location add constraint FKsfehc6uhis4l0rhvmkkyru2lx foreign key (municipality_id) references municipality;
alter table if exists municipality add constraint FKthx6cra4ti5gane6njq0hkprt foreign key (fk_department) references department;
alter table if exists representative add constraint FKggjj3leqdp8qdpjvsm3wm5d7e foreign key (fk_club) references club;
alter table if exists representative add constraint FK48vbhlvmmvj9v74915otr8246 foreign key (fk_document_type) references document_type;
