create table "category_weight$clubs" (id integer not null, email varchar(255), name varchar(255), fk_country integer, fk_municipality integer, primary key (id));
create table club (id integer not null, email varchar(255), name varchar(255), fk_country integer not null, fk_municipality integer, primary key (id));
alter table if exists location add column municipality_id integer;
create table municipality (id integer not null, code integer, name varchar(255), fk_department integer, primary key (id));
create table representative (id integer not null, document_number varchar(255), last_nane varchar(255), name varchar(255), phone_number varchar(255), fk_club integer not null, fk_document_type integer not null, primary key (id));
alter table if exists location drop constraint if exists UKlxduifr1oahk3fyxrnwei7trk;
alter table if exists location add constraint UKlxduifr1oahk3fyxrnwei7trk unique (municipality_id);
create sequence "category_weight$clubs_seq" start with 1 increment by 50;
create sequence club_seq start with 1 increment by 50;
create sequence municipality_seq start with 1 increment by 50;
create sequence representative_seq start with 1 increment by 50;
alter table if exists "category_weight$clubs" add constraint FKaa0o5nh1cilu9p1hhxiqgwfd9 foreign key (fk_country) references country;
alter table if exists "category_weight$clubs" add constraint FKe85abjlh075segtn48vfv2u4s foreign key (fk_municipality) references municipality;
alter table if exists club add constraint FK7syjecp1a87lp35fdyxtputl4 foreign key (fk_country) references country;
alter table if exists club add constraint FK5rny420umgc5r0iet5qenbbly foreign key (fk_municipality) references municipality;
alter table if exists location add constraint FKsfehc6uhis4l0rhvmkkyru2lx foreign key (municipality_id) references municipality;
alter table if exists municipality add constraint FKthx6cra4ti5gane6njq0hkprt foreign key (fk_department) references department;
alter table if exists representative add constraint FKggjj3leqdp8qdpjvsm3wm5d7e foreign key (fk_club) references club;
alter table if exists representative add constraint FK48vbhlvmmvj9v74915otr8246 foreign key (fk_document_type) references document_type;
