create table athlete (id integer not null, birth_date varchar(255), id_number varchar(255), last_name varchar(255), name varchar(255), picture_url varchar(255), sex smallint check (sex between 0 and 1), weight float(53) not null, fk_belt_grade integer, fk_club integer, fk_document_type integer, fk_country integer, primary key (id));
create table categories (id integer not null, sex smallint check (sex between 0 and 1), fk_category_age integer, fk_category_belt_grade integer, fk_category_weight integer, primary key (id));
create table championship (id integer not null, end_event_date timestamp(6), name varchar(255), start_event_date timestamp(6), fk_club integer not null, fk_location integer not null, primary key (id));
create table club_athlete_list (club_id integer not null, athlete_list_id integer not null);
alter table if exists club_athlete_list drop constraint if exists UKq79nkst5dyl9v0ovgu9m0pa8r;
alter table if exists club_athlete_list add constraint UKq79nkst5dyl9v0ovgu9m0pa8r unique (athlete_list_id);
create sequence athlete_seq start with 1 increment by 50;
create sequence categories_seq start with 1 increment by 50;
create sequence championship_seq start with 1 increment by 50;
alter table if exists athlete add constraint FKdy2jjim1bs4uua4isny0x70y9 foreign key (fk_belt_grade) references belt_grade;
alter table if exists athlete add constraint FKeqmqebp2jbghwjsey1fgv42rh foreign key (fk_club) references club;
alter table if exists athlete add constraint FKjqw93h9xfgwbhyo5tiqkiiuql foreign key (fk_document_type) references document_type;
alter table if exists athlete add constraint FKb2gqr88jmxe9m583a8866048r foreign key (fk_country) references country;
alter table if exists categories add constraint FK8uxubv1y5eqp75enx4isfg99d foreign key (fk_category_age) references category_age;
alter table if exists categories add constraint FKcopmh6sop7af5966dbc7mdpj8 foreign key (fk_category_belt_grade) references category_belt_grade;
alter table if exists categories add constraint FKbtoio1dpyep57tu765y5g4drr foreign key (fk_category_weight) references category_weight;
alter table if exists championship add constraint FKio3b5rwak8wl49adodhk7xgmi foreign key (fk_club) references club;
alter table if exists championship add constraint FK6crwfyvqtjqu0w1tauho6vpxv foreign key (fk_location) references location;
alter table if exists club_athlete_list add constraint FK9d4rl15p2701frmywybr11dxw foreign key (athlete_list_id) references athlete;
alter table if exists club_athlete_list add constraint FK7v6h7ibnlrdtsw6d03w6ampd8 foreign key (club_id) references club;
